LOAD DATA LOCAL INFILE 'REPLACE_ME_CSV_FULL_PATH'
INTO TABLE REPLACE_ME_DB_NAME.REPLACE_ME_TABLE_NAME
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Column1, @Column2, @Column3)
SET
`Column1` = NULLIF(@Column1, ''),
`Column2` = NULLIF(@Column2, ''),
`Column3` = NULLIF(@Column3, '');